name: blogapp
description: "Flutter project Blog App."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  fpdart: ^1.1.1
  get_it: ^8.0.3
  hive: ^4.0.0-dev.2
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.1
  intl: ^0.20.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  supabase_flutter: ^2.8.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icons/blogapp.png
    #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_native_splash:
  color: "#121212"
  image: assets/icons/blogapp.png  # PNG centrado
  
  android: true
  ios: true
  web: false


  android_gravity: center          # ❗ evita el estiramiento

  android_12:
    image: assets/icons/blogapp.png
    color: "#121212"
    icon_background_color: "#121212"



